### ISSUE TITLE
anbox session manager is masked

### ISSUE THREAD

**Issue by HumHongeKamyaab** [Fuseteam/systemd-service-files#4]
I am trying to follow instructions here
https://github.com/fuseteam/systemd-service-files#anbox-session-manager

but getting this error
```
Failed to enable unit: Unit file /etc/xdg/systemd/user/anbox-session-manager.service is masked.
```

**Comment by Fuseteam** [comment]
hmmm can you run `ls ~/.config/systemd/user`?

**Comment by Fuseteam** [comment]
@HumHongeKamyaab i do need you to provide the output so i can figure out what's happing in your case

**Comment by YSahil** [comment]
> 
i was also having the similar issue 
i got this output
`anbox.service  anbox-session-manager.service  graphical-session.target.wants  synapse.service`

**Comment by Fuseteam** [comment]
@YSahil that looks good (tho i'm not sure if you're actually using [synapse](https://www.addictivetips.com/ubuntu-linux-tips/use-synapse-to-launch-programs-on-linux/) need synaps.service)
can i see your error when you try to enable it? the `graphical-session.target.wants` folder seems to suggest it was enabled succesfully

**Comment by sakurawald** [comment]
finally, i once can run my `anbox.appmgr` and can `install and run 3-party apps` and even i finish the `google service installation`.
currently, i encouter this problem when i try to launch the anbox by `sudo anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`

![image](https://user-images.githubusercontent.com/10484271/172781685-92ea11c4-8ae1-4756-93ac-5d3abd2ce552.png)

i know my `anbox-session-manager` service is not enable, so i try to enable it manually, and get the following error messages.
![image](https://user-images.githubusercontent.com/10484271/172781875-9e8f7525-6057-4464-a17d-0e287f8ccdd6.png)

the strange thing is that, `sometimes` i can launch the `anbox`, but i  don't know `the real reasons` 
i am in  ubuntu 22.04 LTS

**Comment by sakurawald** [comment]
i tried this commands.
![image](https://user-images.githubusercontent.com/10484271/172782825-d6cdd8f2-b397-48a6-9738-535ebd408ddd.png)

**Comment by sakurawald** [comment]
even after i start the `anbox-session-manager` successfully (maybe the command `sudo systemctl --machine=teeth@.host --user enable --now anbox-session-manager` make it started, but i am not very sure of this), the `anbox` can't be launched .
![image](https://user-images.githubusercontent.com/10484271/172784975-1408637d-fc34-4a5f-b20f-fe4b15f5ff74.png)

**Comment by sakurawald** [comment]
ok, the problem solved.
after you start `anbox-session-manager`, then you should launch the `anbox` without `sudo`
![image](https://user-images.githubusercontent.com/10484271/172787308-cf340ed1-6880-4f51-a6d1-03d7b7dcafe9.png)
![image](https://user-images.githubusercontent.com/10484271/172788700-e619932e-321a-401d-8f9e-aa0119b9f57b.png)

**Comment by Fuseteam** [comment]
> i know my `anbox-session-manager` service is not enable, so i try to enable it manually, and get the following error messages. ![image](https://user-images.githubusercontent.com/10484271/172781875-9e8f7525-6057-4464-a17d-0e287f8ccdd6.png)
> 
> the strange thing is that, `sometimes` i can launch the `anbox`, but i don't know `the real reasons` i am in ubuntu 22.04 LTS

ah now i see you ran it with sudo, this is wrong `systemctl --user` should not be used with sudo. perhaps run
```
sudo systemctl --user disable anbox-session-manager
systemctl --user enable --now anbox-session-manager
```

note that you only need to run the systemctl enable command once.
`systemctl --user enable anbox-session-manager` is a way to tell systemd to automatically start the session manager for you when you start up your computer

**Comment by Fuseteam** [comment]
@YSahil @HumHongeKamyaab can you guys please confirm if you guys are running `systemctl` with or without sudo?
if you ran it with sudo; sudo missing in the readme is not an oversight, you don't need sudo at all for systemd user services

**Comment by Fuseteam** [comment]
closing issue as anbox is now dead
